### ISSUE TITLE
GPG Suite 2022.1 Source Released

### ISSUE THREAD

**Issue by walterrowe** [Free-GPGMail/Free-GPGMail#48] opened 2022-04-08 14:53 UTC
Please update to 2022.1 release.

https://releases.gpgtools.org/GPG_Suite-2022.1.txz

**Comment by bnavigator** [comment] 2022-04-08 16:33
Duplicate of #43. Thanks for the notification. I will try to find some free time over the weekend (unless someone beats me to it with a PR)

**Closed as completed by bnavigator** 2022-04-08 16:33 UTC
