### ISSUE TITLE
PGP/MIME content doesn't render rich text content properly

### ISSUE THREAD

**Issue by walterrowe** [Free-GPGMail/Free-GPGMail#34] opened 2021-12-20 17:53 UTC
GPGsuite 6 / macOS Monterey 12.0.1 / Free-GPGmail 6 2021.2p3

Is this an encoding problem on the originator's end or on GPGmail's end?

<img width="877" alt="Screen Shot 2021-12-20 at 12 49 08 PM" src="https://user-images.githubusercontent.com/7131288/146810566-de5a8e2a-96a0-4765-96c9-ad78fa10551e.png">

<img width="766" alt="Screen Shot 2021-12-20 at 12 51 59 PM" src="https://user-images.githubusercontent.com/7131288/146810762-04d2aed7-c71f-4910-a13b-0d21abb4130e.png">

**Comment by bnavigator** [comment] 2021-12-20 18:12
> Is this an encoding problem on the originator's end or on GPGmail's end?

What if you disable the plugin in `General->Manage Plugins..` and re-open the e-mail after the restart of Mail?

**Comment by walterrowe** [comment] 2021-12-20 19:11
Plugin Disabled
<img width="1030" alt="Screen Shot 2021-12-20 at 2 03 25 PM" src="https://user-images.githubusercontent.com/7131288/146819597-baafa639-6ae3-4b6c-ba00-9b39b8385154.png">

Screen Recording
https://www.walterrowe.com/client/Free-GPGmail-2021.2sp3.mov

**Comment by bnavigator** [comment] 2022-01-02 12:57
BTW you can also install Thunderbird for Mac, configure the IMAP account and check the rendering of the Mail there.

**Comment by bnavigator** [comment] 2022-01-02 15:14
It works for me:

![image](https://user-images.githubusercontent.com/4623504/147880144-9e71974d-203a-4812-b31c-bfb01185722f.png)

**Comment by bnavigator** [comment] 2022-01-02 15:41
Closing as this is now confirmed to be wrong from the Facebook side:

```
% gpg --decrypt Encrypted\ Notification\ from\ Facebook\ \[ARNbCUqkkvW--tuI\].eml
gpg: encrypted with 4096-bit RSA key, ID XXXX, created 2021-08-19
      "Walter Rowe <XXXX>"
Content-Type: multipart/alternative;
	boundary="b1_50bf08d00e7fd42f19839ebf6c8626bf"


--b1_50bf08d00e7fd42f19839ebf6c8626bf
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional //EN"><html ...

```

**Closed as completed by bnavigator** 2022-01-02 15:41 UTC
