### ISSUE TITLE
File > Share > Email Link doesn't work with Free-GPGmail_6.mailbundle 2021.2p3

### ISSUE THREAD

**Issue by walterrowe** [Free-GPGMail/Free-GPGMail#37] opened 2021-12-30 15:25 UTC
When I remove the Free-GPGmail plugin, File > Share > Email Link works from Google Chrome, Safari, etc.
When I install the Free-GPGmail plugin, File > Share > Email Link doesn't work from Google Chrome, Safari, etc.

100 percent reproducible

macOS 12.1 Monterey
GPG-suite 2021.3
Free-GPGmail_6.mailbundle 2021.2p3

<img width="766" alt="Screen Shot 2021-12-30 at 10 17 37 AM" src="https://user-images.githubusercontent.com/7131288/147764419-9e112ca3-e4bb-49cd-aefc-177aefe9bf34.png">

<img width="243" alt="Screen Shot 2021-12-30 at 10 20 05 AM" src="https://user-images.githubusercontent.com/7131288/147764616-2cfbd356-d6ff-48c8-9c48-e5bf386a3c40.png">

**Comment by bnavigator** [comment] 2021-12-30 17:26
Duplicate of #31.

**Closed as completed by bnavigator** 2021-12-30 17:26 UTC
